### PR TITLE
Check if init script exists before trying to execute it

### PR DESCRIPTION
**Pull request by bauerj**
Fix facebook/hhvm#5410

### CODE REVIEW

**Comment by jwatzman** [comment]
I'm not sure I follow the problem in the linked report -- why wouldn't the init script be available? It should be in all of our `hhvm` and `hhvm-nightly` packages.

**Comment by Renegade334** [comment]
The script is being invoked in the pre-installation phase, to shut down any existing hhvm service. The script will only exist in this phase if hhvm is already installed.

**Comment by jwatzman** [comment]
Oops, that makes sense, thanks!

**Comment by Renegade334** [comment]
The 3.7.1 packages were assembled without this patch, which has effectively nuked the new version for package users unless workaround hacks are used. Can we request new 3.7.1 packages for Debian and Ubuntu built with the fixed packaging framework?

**Comment by jwatzman** [comment]
Trusty was built improperly, the others should be fine, I'll do a 3.7.1-1

**Comment by Renegade334** [comment]
Ah, righto.

**Comment by jwatzman** [comment]
Should be fixed now, LMK if not.

**Pull request merged**
